default_experiment:
    datasets: [products, products_seen, products_half, cameras, computers, shoes, watches]
    shots: none
    shots_dataset: null
    cot: False
    reps: 1
    reps_separate: False
    temperature: 0.0
    templates: [baseline, customer, detective, journalist, layperson, plain, security, veryplain]
    crowd_methods: [DawidSkene]
    extra_analysis: []
experiments:
  er_example:
    datasets: [cameras]
    templates: [veryplain]
    extra_analysis: [correlations]
  er_basic:
    extra_analysis: [correlations]
  er_fewshot:
    shots: regular
    crowd_methods: [MajorityVote, Wawa, DawidSkene, GLAD, EBCC, BWA, GoldStandard]
    extra_analysis: [correlations]
  er_multirep:
    datasets: [cameras, computers, shoes, watches]
    reps: 10
    temperature: 2.0
  er_multirep_shots:
    datasets: [cameras, computers, shoes, watches]
    reps: 10
    temperature: 2.0
    shots: regular
  er_uniform_fewshot:
    datasets: [computers]
    reps: 10
    reps_separate: True
    shots: uniform
    extra_analysis: [stdev]
  er_cameras_fewshot:
    datasets: [computers, shoes, watches]
    shots: regular
    shots_dataset: cameras
  er_cot:
    datasets: [products]
    cot: True
    templates: [baseline]
  er_cot_fewshot:
    datasets: [products]
    cot: True
    shots: uniform
    templates: [baseline]
custom_crowds:
    er_custom_cot:
        experiments:
            er_basic: [baseline]
            er_fewshot: [baseline]
            er_cot: [baseline]
            #er_cot_fewshot: [baseline]
        crowd_methods: [MajorityVote, Wawa, DawidSkene, GLAD, EBCC, BWA, GoldStandard]
            
