default_experiment:
    datasets: [products, products_seen, products_half, cameras, computers, shoes, watches]
    shots: none
    shots_dataset: null
    cot: False
    reps: 1
    temperature: 0.0
    templates: [baseline, customer, detective, journalist, layperson, plain, security, veryplain]
experiments:
  er_example:
    datasets: [cameras]
    templates: [veryplain]
  er_basic: {}
  er_fewshot:
    shots: regular
  er_multirep:
    datasets: [cameras, computers, shoes, watches]
    reps: 10
    temperature: 2.0
  er_multirep_shots:
    datasets: [cameras, computers, shoes, watches]
    reps: 10
    temperature: 2.0
    shots: regular
  er_uniform_fewshot:
    datasets: [computers]
    reps: 10
    shots: uniform
  er_cameras_fewshot:
    datasets: [computers, shoes, watches]
    shots: regular
    shots_dataset: cameras
  er_cot:
    datasets: [products]
    cot: True
    templates: [baseline]
